### ISSUE TITLE
I think it is necessary to add the first line to the ignoreregex

### ISSUE THREAD

**Issue by jackpxyz** [wpkc/fail2ban-filter-ninjafirewall-logs#2]
It also seems that in recent versions of ninjafirewall the critical entries have number 3 now.

checking the locks lately it is not adding ip for what I tried fail2ban-regex /var/www/html/wp-content/nfwlog/firewall_*.php /etc/fail2ban/filter.d/ninjafirewall-logs.conf and it seems that it is giving an error with the first line `'<?php exit; ?>\n'`

Running tests
=============

Use   failregex file : /var/www/html/wp-content/nfwlog/firewall_2023-03.php
Wrong config file: File contains no section headers.
file: '/var/www/html/wp-content/nfwlog/firewall_2023-03.php', line: 1
`'<?php exit; ?>\n'`
ERROR: failed to load filter /var/www/html/wp-content/nfwlog/firewall_2023-03.php

**Comment by jackpxyz** [comment]
I change the filter with de options:

startline = ^<?php exit; ?>$
ignoreregex = ^<?php exit; ?>

and the error still there

**Comment by wpkc** [comment]
What version of fail2ban are you using?  

I tried some tests, and fail2ban is automatically ignoring the first line of the ninjafirewall file.  This is what I would expect, since it should ignore any line that it can't find a recognizable date-time stamp.

Also, you need to modify your use of fail2ban-regex for this test.  Using wildcards does not seem to work.  So specify an absolute file name.  To test ignoreregex, you need to add it as a third parameter for the command, like so...
`fail2ban <log file> <filter regex, or filter file path> <ignoreregex, or filter file path>`
That means you will need to enter the filter file path twice if you want to test it from the filter file.

Also, use the --print-all-missed option.  The command output will show zero ignored lines, but if you --print-all-missed, you will see that the first line is automatically being ignored.  So no ignoreregex line is needed.

If you want to see the filter in action in the real world, try setting maxretry for the filter in jail.local to 2, or even 1 if you want to see a lot of bans.

**Comment by jackpxyz** [comment]
I using version 0.11.2-6

You are correct wildcard is not working, with absolute file name work as expected and the first line is ignored. The filter is working as expected, I have maxretry in 1, my woocommerce shop recive many hack atemps.

I only needed to add the critics number to the filter that apparently changed it to number 3.

Thank you very much for your time.

**Comment by wpkc** [comment]
I'm using the Debian distribution, which is currently at v0.9, so I suppose there could be differences in behavior.

Here is the definition of the log levels in NinjaFirewall, Version 4.5.6, in file /ninjafirewall/lib/logs_firewall_log.php, line 106...

`$levels = array( '', 'MEDIUM', 'HIGH', 'CRITICAL', 'ERROR', 'UPLOAD', 'INFO', 'DEBUG_ON' );`

Since arrays start with an index number of 0, that works out to:

1 = MEDIUM
2 = HIGH
3 = CRITICAL
4 = ERROR
5 = UPLOAD
6 = INFO
7 = DEBUG_ON

So yes, you are right, they changed the values; reversed the actually.  3 is critical now.  The following should catch medium, high, and critical events.

`failregex = \[(?:[\d\.]{1,8})\] \[(?:[\w\.\-]{4,80})\] \[\#(?:\d{5,9})\] \[(?:\d{1,6})\] \[[123]\] \[<HOST>\] \[(?:\d{3})\] \[(?:POST|GET|PUT|PATCH|DELETE)\] \[`

I don't exactly agree with how they define all medium and high events though.  They define bots trying to brute force your login page as medium, and search engines trying to index your site through the REST API as high.  That seems backwards to me.

**Comment by wpkc** [comment]
I updated the master with the latest filter
